services:
  microservice-chat-app-backend:
    image: pacman-app-backend
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: pacman-app-backend
    command: "uvicorn --factory app.main:create_app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "${API_PORT}:8000"
    env_file:
      - ../.env
    networks:
      - backend

networks:
  backend:
    driver: bridge