services:
  pacman-app-backend:
    container_name: pacman-app-backend
    image: pacman-app-backend
    build:
      context: ..
      dockerfile: Dockerfile
    command: "uvicorn --factory app.main:create_app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "${API_PORT}:8000"
    env_file:
      - ../.env
    depends_on:
      - mongo
      - cache
    networks:
      - backend

networks:
  backend:
    driver: bridge