services:
  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus-pacman-backend-app
    restart: unless-stopped
    ports:
      - "9090:9090"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:9090/-/ready" ]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - ../resources/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - backend

  grafana:
    image: grafana/grafana:9.4.7
    container_name: grafana-pacman-backend-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:3000" ]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - grafana_data:/var/lib/grafana
      - ../resources/config/grafana/provisioning:/etc/grafana/provisioning
      - ../resources/config/grafana/provisioning/dashboards-json:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    env_file:
      - ../.env
    depends_on:
      - prometheus
    networks:
      - backend

volumes:
  grafana_data:
  prometheus_data:

networks:
  backend:
    driver: bridge