services:
  pacman-app-backend:
    container_name: backend-temporary-app
    image: backend-temporary-app
    build:
      context: ..
      dockerfile: Dockerfile
    command: "uvicorn --factory app.main:create_app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "${API_PORT}:8000"
    env_file:
      - ../.env
    depends_on:
      - postgres
    networks:
      - seventh_laboratory

networks:
  seventh_laboratory:
    driver: bridge